storage:
  dbPath: /data/db
  wiredTiger:
    engineConfig:
      cacheSizeGB: 200

net:
  bindIpAll: true
  # This port is inside the container namespace. The host port is mapped in compose.yml.
  port: 27017

processManagement:
  timeZoneInfo: /usr/share/zoneinfo

setParameter:
  diagnosticDataCollectionEnabled: false
